use ExtUtils::MakeMaker;
#
# This Makefile.PL generated on Tue Mar  7 17:28:15 PST 2006 by nwiger
# running the magical "perlpkg" script.
#
# Eeek! I didn't star with h2xs. Oops.
#
WriteMakefile(
    NAME          => 'SQL::Abstract',
    VERSION_FROM  => 'lib/SQL/Abstract.pm',   # finds 
    PREREQ_PM     => {},            # e.g., Module::Name => 1.1
    ABSTRACT_FROM => 'lib/SQL/Abstract.pm',   # retrieve abstract from module
    AUTHOR        => 'Nate Wiger,IT/OG,44760 (nwiger)',      # author name
);
