---
abstract: 'Generate SQL from Perl data structures'
author:
  - 'Nathan Wiger <nate@wiger.org>'
build_requires:
  Clone: 0.31
  ExtUtils::MakeMaker: 6.42
  Test::Builder: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Abstract
no_index:
  directory:
    - inc
    - t
requires:
  List::Util: 0
  Scalar::Util: 0
  perl: 5.6.1
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.57
