# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SQL-Abstract
version:      1.49_03
version_from: lib/SQL/Abstract.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    List::Util:                    0
    Scalar::Util:                  0
    Test::Builder:                 0
    Test::Deep:                    0
    Test::Exception:               0
    Test::More:                    0
    Test::Warn:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
